# Generated by Django 6.0.2 on 2026-02-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
