# Generated by Django 6.0.2 on 2026-02-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-duration'], 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
